In [119]:
import pandas as pd
import numpy as np
price = pd.read_csv('price.csv')

In [124]:
price['return'] = np.log(price['Close']) - np.log(price['Close'].shift(1))

price.ix [price.Symbol!= price.Symbol.shift(1),'return'] = np.nan

In [132]:
price.tail

<bound method DataFrame.tail of        Symbol       Date    Volume      Close    return
0           A  2015/7/31   2243000  40.950001       NaN
1           A  2015/7/30   2440400  40.970001  0.000488
2           A  2015/7/29   2011200  40.400002 -0.014010
3           A  2015/7/28   2765200  40.450001  0.001237
4           A  2015/7/27   5261300  39.610001 -0.020985
5           A  2015/7/24   1844900  39.310001 -0.007603
6           A  2015/7/23   1708800  40.250000  0.023631
7           A  2015/7/22   2948200  40.330002  0.001986
8           A  2015/7/21   1150300  39.570000 -0.019024
9           A  2015/7/20   1155200  40.060001  0.012307
10          A  2015/7/17   2412400  39.950001 -0.002750
11          A  2015/7/16   1826300  40.340000  0.009715
12          A  2015/7/15   2247700  40.130001 -0.005219
13          A  2015/7/14   2800900  40.490002  0.008931
14          A  2015/7/13   1579700  39.959999 -0.013176
15          A  2015/7/10   2107100  39.400002 -0.014113
16          A   2015/7/9   2237900  38.919998 -0.012258
17          A   2015/7/8   3389000  38.750000 -0.004377
18          A   2015/7/7   2927800  39.790001  0.026485
19          A   2015/7/6   2507900  39.360001 -0.010866
20          A   2015/7/2   2156000  39.580002  0.005574
21          A   2015/7/1   4486400  39.259998 -0.008118
22          A  2015/6/30   3027900  38.580002 -0.017472
23          A  2015/6/29   2514000  38.740002  0.004139
24          A  2015/6/26   3350500  40.020000  0.032507
25          A  2015/6/25   5265800  39.949998 -0.001751
26          A  2015/6/24   6127700  40.089648  0.003490
27          A  2015/6/23   2053600  39.501121 -0.014789
28          A  2015/6/22   3909300  39.710600  0.005289
29          A  2015/6/19   2658800  39.391399 -0.008071
...       ...        ...       ...        ...       ...
248946    ZTS  2013/9/12   2881300  30.579025  0.000966
248947    ZTS  2013/9/11   6367900  30.824995  0.008012
248948    ZTS  2013/9/10   5024400  30.451121 -0.012203
248949    ZTS   2013/9/9   2723800  30.096923 -0.011700
248950    ZTS   2013/9/6   5245900  30.116602  0.000654
248951    ZTS   2013/9/5   5688100  29.841114 -0.009189
248952    ZTS   2013/9/4   3187200  29.211431 -0.021327
248953    ZTS   2013/9/3   2052100  28.955622 -0.008796
248954    ZTS  2013/8/30   2296300  28.680134 -0.009560
248955    ZTS  2013/8/29   1590600  28.994976  0.010918
248956    ZTS  2013/8/28   7067300  29.093364  0.003388
248957    ZTS  2013/8/27   8103500  28.729329 -0.012592
248958    ZTS  2013/8/26   7179000  29.319657  0.020340
248959    ZTS  2013/8/23   2531600  29.713210  0.013334
248960    ZTS  2013/8/22   3030800  29.388530 -0.010987
248961    ZTS  2013/8/21   3531400  29.368852 -0.000670
248962    ZTS  2013/8/20   3804100  29.742726  0.012650
248963    ZTS  2013/8/19   2480600  29.388530 -0.011980
248964    ZTS  2013/8/16   3678800  29.516433  0.004343
248965    ZTS  2013/8/15   5818900  29.536112  0.000666
248966    ZTS  2013/8/14   3858200  29.654176  0.003989
248967    ZTS  2013/8/13   3116200  29.959181  0.010233
248968    ZTS  2013/8/12   5793700  29.841114 -0.003949
248969    ZTS   2013/8/9   2784100  30.411765  0.018942
248970    ZTS   2013/8/8   7161900  30.736446  0.010620
248971    ZTS   2013/8/7   5920100  30.736446  0.000000
248972    ZTS   2013/8/6  12471200  30.628218 -0.003527
248973    ZTS   2013/8/5   7283300  30.746285  0.003847
248974    ZTS   2013/8/2   5187500  30.441282 -0.009970
248975    ZTS   2013/8/1   8105500  29.673854 -0.025533

[248976 rows x 5 columns]>