In [67]:
import pandas as pd
import numpy as np

volume = pd.read_csv('volume.csv',header =4)

lc = volume.ix[:,0:2]
sc = volume.ix[:,3:5]
spx_v  = volume.ix[:,5:6]
spx_v

            SPX
0    1181.27000
1    1203.60000
2    1180.59000
3    1156.85000
4    1191.50000
5    1191.33000
6    1234.18000
7    1220.33000
8    1228.81000
9    1207.01000
10   1249.48000
11   1248.29000
12   1280.08000
13   1280.66000
14   1294.87000
15   1310.61000
16   1270.09000
17   1270.20000
18   1276.66000
19   1303.82000
20   1335.85000
21   1377.94000
22   1400.63000
23   1418.30000
24   1438.24000
25   1406.82000
26   1420.86000
27   1482.37000
28   1530.62000
29   1503.35000
..          ...
90   1379.32000
91   1406.58000
92   1440.67000
93   1412.16000
94   1416.18000
95   1426.19000
96   1498.11093
97   1514.67827
98   1569.18587
99   1597.56567
100  1630.74189
101  1606.27761
102  1685.72502
103  1632.97115
104  1681.54666
105  1756.54463
106  1805.81269
107  1848.35652
108  1782.58697
109  1859.44937
110  1872.33518
111  1883.95013
112  1923.57266
113  1960.23124
114  1930.67387
115  2003.36770
116  1972.28515
117  2018.05450
118  2067.56204
119  2063.83000

[120 rows x 1 columns]

In [28]:
volume

        Month        ADV  Volatility    ADV.1  Volatility.1         SPX
0    Jan-2005  4,145,429      0.2306  414,942        0.3705  1181.27000
1    Feb-2005  3,934,471      0.2419  400,271        0.3787  1203.60000
2    Mar-2005  3,905,479      0.2326  405,187        0.3552  1180.59000
3    Apr-2005  4,121,933      0.2808  401,821        0.4279  1156.85000
4    May-2005  3,621,475      0.2310  391,428        0.4028  1191.50000
5    Jun-2005  3,413,944      0.1986  399,808        0.3539  1191.33000
6    Jul-2005  3,561,657      0.2269  382,196        0.3731  1234.18000
7    Aug-2005  3,266,285      0.2062  374,321        0.3553  1220.33000
8    Sep-2005  3,874,930      0.2337  399,728        0.3521  1228.81000
9    Oct-2005  4,351,479      0.3023  424,493        0.4258  1207.01000
10   Nov-2005  3,929,000      0.2402  414,693        0.3814  1249.48000
11   Dec-2005  3,608,421      0.2044  407,982        0.3321  1248.29000
12   Jan-2006  4,573,083      0.2518  454,713        0.3560  1280.08000
13   Feb-2006  4,078,253      0.2359  435,596        0.3608  1280.66000
14   Mar-2006  4,001,277      0.2031  444,629        0.3313  1294.87000
15   Apr-2006  4,215,267      0.2397  450,302        0.3571  1310.61000
16   May-2006  4,393,611      0.2494  482,387        0.4011  1270.09000
17   Jun-2006  4,295,478      0.2670  497,533        0.4428  1270.20000
18   Jul-2006  4,232,139      0.2935  438,726        0.4771  1276.66000
19   Aug-2006  3,824,133      0.2267  415,073        0.3759  1303.82000
20   Sep-2006  4,303,286      0.2211  432,411        0.3466  1335.85000
21   Oct-2006  4,453,965      0.2381  455,671        0.3576  1377.94000
22   Nov-2006  4,446,941      0.2188  446,831        0.3501  1400.63000
23   Dec-2006  4,076,911      0.1800  413,857        0.3023  1418.30000
24   Jan-2007  4,912,171      0.2103  439,049        0.3257  1438.24000
25   Feb-2007  4,573,329      0.2304  478,730        0.3472  1406.82000
26   Mar-2007  4,959,523      0.2176  495,705        0.3644  1420.86000
27   Apr-2007  4,807,581      0.2096  484,313        0.3278  1482.37000
28   May-2007  4,786,477      0.2056  517,678        0.3475  1530.62000
29   Jun-2007  5,027,231      0.2196  525,043        0.3249  1503.35000
..        ...        ...         ...      ...           ...         ...
90   Jul-2012  5,163,324      0.2987  469,582        0.4077  1379.32000
91   Aug-2012  4,395,483      0.1720  402,341        0.2596  1406.58000
92   Sep-2012  5,344,209      0.2169  486,602        0.2885  1440.67000
93   Oct-2012  5,213,923      0.1991  437,865        0.2371  1412.16000
94   Nov-2012  5,078,885      0.2859  445,005        0.3801  1416.18000
95   Dec-2012  4,874,791      0.2113  440,816        0.2598  1426.19000
96   Jan-2013  5,541,096      0.2349  459,169        0.3811  1498.11093
97   Feb-2013  5,364,641      0.2170  470,832        0.3504  1514.67827
98   Mar-2013  4,868,824      0.2185  481,469        0.3457  1569.18587
99   Apr-2013  5,021,384      0.2200  449,142        0.3500  1597.56567
100  May-2013  4,832,687      0.2310  480,666        0.3807  1630.74189
101  Jun-2013  5,188,910      0.2385  517,655        0.3798  1606.27761
102  Jul-2013  4,353,630      0.2404  416,008        0.3817  1685.72502
103  Aug-2013  3,943,886      0.2294  417,123        0.3565  1632.97115
104  Sep-2013  4,413,243      0.2168  484,951        0.3538  1681.54666
105  Oct-2013  4,572,171      0.2083  509,581        0.3474  1756.54463
106  Nov-2013  4,231,229      0.2120  500,253        0.3635  1805.81269
107  Dec-2013  4,132,350      0.2101  494,996        0.3678  1848.35652
108  Jan-2014  4,970,588      0.2056  594,407        0.3684  1782.58697
109  Feb-2014  4,971,952      0.2198  575,480        0.3650  1859.44937
110  Mar-2014  4,481,910      0.2214  658,935        0.3729  1872.33518
111  Apr-2014  4,726,705      0.2283  549,783        0.3835  1883.95013
112  May-2014  3,813,411      0.2130  541,937        0.3875  1923.57266
113  Jun-2014  3,698,389      0.2052  563,948        0.3787  1960.23124
114  Jul-2014  3,889,724      0.1897  487,896        0.3590  1930.67387
115  Aug-2014  3,328,178      0.1862  449,763        0.3448  2003.36770
116  Sep-2014  3,854,627      0.1817  516,212        0.3318  1972.28515
117  Oct-2014  4,988,077      0.2084  592,826        0.3621  2018.05450
118  Nov-2014  3,881,341      0.2250  505,978        0.3889  2067.56204
119  Dec-2014  4,657,497      0.2424  597,462        0.4161  2063.83000

[120 rows x 6 columns]