In [110]:
#get data from web

import urllib
import datetime
import numpy as np
import pandas as pd

### get the url for the downloadable csv-file data
def make_url(ticker_symbol, start_date, end_date):
    base_url = "http://ichart.finance.yahoo.com/table.csv?s="
    # print ticker_symbol
    a = start_date
    b = end_date
    dt_url = '%s&a=%d&b=%d&c=%d&d=%d&e=%d&f=%d&g=d&ignore=.csv'% (ticker_symbol, a.month-1, a.day, a.year, b.month-1, b.day,b.year)
    return base_url + dt_url

### create a path to save the file downloaded from web
#mac
#output_path = "/Users/apple/Downloads/lecture4" ## <======Please change to your own directory
#win
output_path = "C:/Users/bjd/Desktop/data" ## <======Please change to your own directory


def make_filename(ticker_symbol):
    return output_path + "/" + ticker_symbol + ".csv"
    

### pull the data out from web and store the file in the path that designed above
def pull_historical_data(ticker_symbol, start_date, end_date):
    try:
        urllib.urlretrieve(make_url(ticker_symbol, start_date, end_date), make_filename(ticker_symbol))
    except urllib.ContentTooShortError as e:
        outfile = open(make_filename(ticker_symbol), "w")
        outfile.write(e.content)
        outfile.close()

In [119]:

#changing directory

import os
#mac
#os.chdir( "/Users/apple/Downloads/lecture4/")
#win
os.chdir( "C:/Users/bjd/Desktop/data") 



#symbols = ['AAL','AAPL','HPQ','AMD','MSFT','GOOG','T','COST','A','LB','RAD','NVGN','SCON','MMM','STZ','UAL','JAZZ','GE','UPS','SNE']
symbols = ['AAL','AAPL','HPQ','AMD','MSFT','GOOG','T','COST','A','LB','RAD','NVGN','SCON','MMM','UAL','STZ','JAZZ','GE','UPS','SNE']
#symbols = ['VNET','AAPL']

start = datetime.date(2010,1,1)
end = datetime.date(2016,1,1)
rf = 0

#for passive equity portfolio:
ErM = 0.16
SigmaRM  = 0.23


#portfolio data
for symbol in symbols:
    pull_historical_data(symbol,start,end) ###<=== get historical time-series data for  HPQ
    np.genfromtxt('%s.csv' %symbol, delimiter=",", skip_header=1)

In [120]:
data = dict()
for symbol in symbols:
    # create a new array in this slot
    data[symbol] = pd.read_csv('%s.csv' %symbol, sep=',', na_values=".")

#print data['AAPL']

#market data
pull_historical_data('SPY',start,end) ###<=== get historical time-series data for  HPQ
np.genfromtxt('SPY.csv', delimiter=",", skip_header=1) 
SPY = pd.read_csv('SPY.csv', sep=',', na_values=".")
SPY

,Date,Open,High,Low,Close,Volume,Adj Close
0,2015-12-31,205.130005,205.889999,203.869995,203.869995,102929500,198.719589
1,2015-12-30,207.110001,207.210007,205.759995,205.929993,63317700,200.727544
2,2015-12-29,206.509995,207.789993,206.470001,207.399994,92640700,202.160408
3,2015-12-28,204.860001,205.259995,203.940002,205.210007,65899900,200.025747
4,2015-12-24,205.720001,206.330002,205.419998,205.679993,48539600,200.483860
5,2015-12-23,204.690002,206.070007,204.580002,206.020004,110987200,200.815282
6,2015-12-22,202.720001,203.850006,201.550003,203.500000,111026200,198.358941
7,2015-12-21,201.410004,201.880005,200.089996,201.669998,99094300,196.575171
8,2015-12-18,202.770004,202.929993,199.830002,200.020004,251393500,194.966861
9,2015-12-17,208.399994,208.479996,204.839996,204.860001,173092500,198.503195
10,2015-12-16,206.369995,208.389999,204.800003,208.029999,197017000,201.574828
11,2015-12-15,204.699997,206.110001,202.869995,205.029999,154069600,198.667918
12,2015-12-14,202.070007,203.050003,199.949997,202.899994,182385200,196.604007
13,2015-12-11,203.350006,204.139999,201.509995,201.880005,211173300,195.615668
14,2015-12-10,205.419998,207.429993,205.139999,205.869995,115196800,199.481849
15,2015-12-09,206.190002,208.679993,204.179993,205.339996,162401500,198.968296
16,2015-12-08,206.490005,208.289993,205.779999,206.949997,103372400,200.528339
17,2015-12-07,209.229996,209.729996,207.199997,208.350006,102027100,201.884906
18,2015-12-04,205.610001,209.970001,205.610001,209.619995,192913900,203.115487
19,2015-12-03,208.830002,209.149994,204.750000,205.610001,166224200,199.229922
20,2015-12-02,210.619995,211.000000,208.229996,208.529999,108441300,202.059313
21,2015-12-01,209.440002,210.820007,209.110001,210.679993,97858400,204.142593
22,2015-11-30,209.750000,209.889999,208.559998,208.690002,112822700,202.214352
23,2015-11-27,209.429993,209.800003,208.860001,209.559998,37317800,203.057351
24,2015-11-25,209.500000,209.740005,209.009995,209.320007,51980100,202.824808
25,2015-11-24,207.869995,209.830002,207.410004,209.350006,98874400,202.853876
26,2015-11-23,209.380005,209.979996,208.520004,209.070007,64931200,202.582565
27,2015-11-20,209.449997,210.119995,208.860001,209.309998,94011500,202.815108
28,2015-11-19,208.589996,209.050003,208.199997,208.550003,88220500,202.078697
29,2015-11-18,206.039993,208.899994,205.990005,208.729996,121342500,202.253104
...,...,...,...,...,...,...,...
1480,2010-02-16,108.860001,109.849998,107.820000,109.739998,159317500,94.691245
1481,2010-02-12,106.989998,108.099998,106.510002,108.040001,304622100,93.224370
1482,2010-02-11,106.870003,108.250000,106.250000,108.129997,223591600,93.302025
1483,2010-02-10,107.050003,107.599998,106.110001,107.010002,240511500,92.335616
1484,2010-02-09,107.129997,108.150002,106.269997,107.220001,337820500,92.516818
1485,2010-02-08,106.739998,107.330002,105.809998,105.889999,224166900,91.369200
1486,2010-02-05,106.559998,106.879997,104.580002,106.660004,493585800,92.033613
1487,2010-02-04,108.980003,109.029999,106.419998,106.440002,356715700,91.843781
1488,2010-02-03,109.879997,110.480003,109.510002,109.830002,172730700,94.768907
1489,2010-02-02,109.260002,110.589996,108.879997,110.379997,216327900,95.243481
1490,2010-02-01,108.150002,109.070000,107.500000,109.059998,187865000,94.104494
1491,2010-01-29,109.040001,109.800003,107.220001,107.389999,310677600,92.663504
1492,2010-01-28,110.190002,110.250000,107.910004,108.570000,316104000,93.681690
1493,2010-01-27,109.169998,110.080002,108.330002,109.830002,271863600,94.768907
1494,2010-01-26,109.339996,110.470001,109.040001,109.309998,211168800,94.320211
1495,2010-01-25,110.209999,110.410004,109.410004,109.769997,186937500,94.717130
1496,2010-01-22,111.199997,111.739998,109.089996,109.209999,345942400,94.233925
1497,2010-01-21,113.919998,114.269997,111.559998,111.699997,344859600,96.382467
1498,2010-01-20,114.279999,114.449997,112.980003,113.889999,216490200,98.272153
1499,2010-01-19,113.620003,115.129997,113.589996,115.059998,139172700,99.281708
1500,2010-01-15,114.730003,114.839996,113.199997,113.639999,212283100,98.056435
1501,2010-01-14,114.489998,115.139999,114.419998,114.930000,115718800,99.169537
1502,2010-01-13,113.949997,114.940002,113.370003,114.620003,161822000,98.902050
1503,2010-01-12,113.970001,114.209999,113.220001,113.660004,163333500,98.073696
1504,2010-01-11,115.080002,115.129997,114.239998,114.730003,106375700,98.996966
1505,2010-01-08,113.889999,114.620003,113.660004,114.570000,126402800,98.858904
1506,2010-01-07,113.500000,114.330002,113.180000,114.190002,131091100,98.531016
1507,2010-01-06,113.519997,113.989998,113.430000,113.709999,116074400,98.116836
1508,2010-01-05,113.260002,113.680000,112.849998,113.629997,111579900,98.047805
1509,2010-01-04,112.370003,113.389999,111.510002,113.330002,118944600,97.788948

In [121]:
#Converting to returns
# assume rf = 0, in practice, rate of return on bills is on the order of only about .01% per day,  so total and excess returns are almost indistinguishable. 

def returns(data):
        data['excess_return'] = np.log(data['Adj Close']/data['Adj Close'].shift(1))-rf

returns(SPY)

for i in data:
    returns(data[i])

data['AAL']

,Date,Open,High,Low,Close,Volume,Adj Close,excess_return
0,2015-12-31,42.540001,42.570000,41.830002,42.349998,6788900,41.788657,NaN
1,2015-12-30,43.639999,43.639999,42.459999,42.799999,5463600,42.232693,0.010570
2,2015-12-29,43.250000,43.619999,43.029999,43.500000,4006900,42.923415,0.016223
3,2015-12-28,43.619999,44.040001,42.910000,43.230000,4148000,42.656994,-0.006226
4,2015-12-24,43.270000,44.189999,43.110001,43.810001,3307000,43.229308,0.013327
5,2015-12-23,42.779999,43.389999,42.430000,43.290001,6093600,42.716200,-0.011940
6,2015-12-22,42.560001,43.080002,42.360001,42.900002,5704700,42.331370,-0.009050
7,2015-12-21,41.349998,42.430000,41.349998,42.400002,6597500,41.837997,-0.011723
8,2015-12-18,41.610001,42.310001,40.700001,41.090000,17810000,40.545360,-0.031384
9,2015-12-17,43.330002,43.950001,42.450001,42.459999,7225000,41.897199,0.032798
10,2015-12-16,42.990002,43.490002,42.119999,43.200001,7850900,42.627392,0.017278
11,2015-12-15,41.970001,42.820000,41.919998,42.599998,7097300,42.035343,-0.013986
12,2015-12-14,42.259998,42.869999,41.080002,41.770000,10750500,41.216347,-0.019676
13,2015-12-11,43.279999,43.590000,42.060001,42.090000,10235200,41.532105,0.007632
14,2015-12-10,43.790001,44.480000,43.540001,44.090000,7948000,43.505595,0.046423
15,2015-12-09,44.299999,45.189999,43.189999,43.650002,8001000,43.071429,-0.010030
16,2015-12-08,45.099998,45.509998,44.070000,44.549999,9043700,43.959497,0.020409
17,2015-12-07,45.349998,46.490002,45.220001,45.779999,8911700,45.173193,0.027235
18,2015-12-04,43.820000,44.990002,43.820000,44.970001,9460900,44.373932,-0.017852
19,2015-12-03,43.650002,44.599998,42.919998,43.270000,7235300,42.696464,-0.038536
20,2015-12-02,44.090000,44.529999,43.529999,43.820000,8010400,43.239173,0.012631
21,2015-12-01,41.470001,43.299999,41.299999,43.259998,8912900,42.686595,-0.012862
22,2015-11-30,41.750000,41.990002,40.980000,41.259998,6450900,40.713104,-0.047335
23,2015-11-27,41.380001,42.250000,41.169998,41.689999,3066600,41.137405,0.010368
24,2015-11-25,41.349998,41.500000,40.959999,41.310001,4276600,40.762445,-0.009157
25,2015-11-24,41.020000,41.639999,40.450001,41.230000,7578000,40.683503,-0.001939
26,2015-11-23,42.110001,42.740002,41.810001,42.299999,4166100,41.739320,0.025621
27,2015-11-20,42.400002,42.709999,42.049999,42.200001,5656000,41.640647,-0.002367
28,2015-11-19,41.939999,42.730000,41.889999,42.299999,6545500,41.739320,0.002367
29,2015-11-18,42.320000,42.320000,41.009998,41.750000,11071100,41.196611,-0.013088
...,...,...,...,...,...,...,...,...
1480,2010-02-16,6.930000,7.000000,6.750000,6.880000,21834000,6.697137,0.011696
1481,2010-02-12,6.270000,6.910000,6.190000,6.810000,17096200,6.628998,-0.010226
1482,2010-02-11,6.300000,6.520000,6.220000,6.320000,14084500,6.152021,-0.074673
1483,2010-02-10,6.390000,6.430000,6.210000,6.310000,9782200,6.142287,-0.001583
1484,2010-02-09,6.150000,6.490000,6.150000,6.440000,20482500,6.268832,0.020393
1485,2010-02-08,5.880000,6.110000,5.820000,5.930000,9765900,5.772387,-0.082504
1486,2010-02-05,5.500000,6.030000,5.430000,5.890000,18555800,5.733450,-0.006768
1487,2010-02-04,5.820000,5.820000,5.470000,5.490000,11591200,5.344082,-0.070328
1488,2010-02-03,5.940000,5.980000,5.650000,5.660000,9137400,5.509563,0.030496
1489,2010-02-02,5.650000,6.000000,5.620000,5.960000,14363700,5.801590,0.051647
1490,2010-02-01,5.430000,5.630000,5.350000,5.600000,10965100,5.451158,-0.062304
1491,2010-01-29,5.230000,5.610000,5.170000,5.310000,19094600,5.168866,-0.053175
1492,2010-01-28,4.990000,5.220000,4.710000,5.140000,19157300,5.003384,-0.032539
1493,2010-01-27,5.100000,5.170000,4.470000,4.860000,21655400,4.730827,-0.056014
1494,2010-01-26,5.210000,5.280000,5.050000,5.050000,8787500,4.915777,0.038350
1495,2010-01-25,5.340000,5.500000,5.150000,5.220000,8168200,5.081258,0.033109
1496,2010-01-22,5.480000,5.520000,5.110000,5.240000,11463400,5.100726,0.003824
1497,2010-01-21,5.880000,5.960000,5.420000,5.460000,15641000,5.314879,0.041127
1498,2010-01-20,5.650000,5.890000,5.610000,5.740000,13289100,5.587437,0.050010
1499,2010-01-19,5.500000,5.730000,5.500000,5.640000,7807700,5.490095,-0.017575
1500,2010-01-15,5.640000,5.840000,5.430000,5.500000,10985300,5.353816,-0.025136
1501,2010-01-14,5.460000,5.710000,5.410000,5.590000,12767100,5.441424,0.016231
1502,2010-01-13,5.120000,5.500000,5.020000,5.480000,16400500,5.334348,-0.019874
1503,2010-01-12,5.060000,5.150000,4.960000,5.080000,7870300,4.944979,-0.075794
1504,2010-01-11,5.130000,5.230000,4.940000,5.040000,10952900,4.906042,-0.007905
1505,2010-01-08,5.270000,5.430000,5.060000,5.140000,12760000,5.003384,0.019647
1506,2010-01-07,5.060000,5.430000,5.050000,5.240000,14033400,5.100726,0.019268
1507,2010-01-06,5.190000,5.380000,5.000000,5.090000,16597900,4.954714,-0.029043
1508,2010-01-05,4.790000,5.370000,4.710000,5.310000,25212000,5.168866,0.042314
1509,2010-01-04,4.840000,4.940000,4.660000,4.770000,9837300,4.643219,-0.107245

In [122]:
#regression function

In [123]:
import statsmodels.api as sm

def reg(y,X):
    X = sm.add_constant(X)
    res = sm.OLS(y, X, missing='drop').fit()

    #print(res.summary())
    #print np.std(res.resid)
    alpha,beta = res.params
    return (alpha,beta, np.std(res.resid))
            
print reg(data['AAPL']['excess_return'],SPY['excess_return'])
a,b,c = reg(data['AAPL']['excess_return'],SPY['excess_return'])

(-0.00042663257658199832, 0.93628709229609497, 0.013976272137633696)

# loop all stocks

In [124]:
result = np.empty( shape=(0, 3))
for i in data:
    reg(data[i]['excess_return'],SPY['excess_return'])
    #print i
    #print reg(data[i]['excess_return'],SPY['excess_return'])
    result = np.r_[result,[reg(data[i]['excess_return'],SPY['excess_return'])]]

data1 = pd.DataFrame(result,columns=['alpha','beta','sigma(firm-specific)'],index=data.keys())
data1

         alpha      beta  sigma(firm-specific)
GOOG -0.000128  0.976321              0.012773
A     0.000258  1.485959              0.012521
RAD  -0.000494  1.290410              0.028099
SNE   0.000657  1.118305              0.018541
LB   -0.000826  1.062053              0.013178
AAL  -0.000791  1.415923              0.028241
AAPL -0.000427  0.936287              0.013976
JAZZ -0.001255  1.329444              0.024631
AMD   0.001563  1.609789              0.027665
NVGN  0.001802  0.610269              0.086195
UPS  -0.000046  0.854974              0.007598
MMM  -0.000037  0.972713              0.007066
GE   -0.000070  1.120193              0.008675
COST -0.000463  0.664951              0.008622
T    -0.000047  0.630372              0.007418
SCON  0.003675  0.828536              0.059450
STZ  -0.000986  0.984702              0.016652
HPQ   0.000909  1.114923              0.018309
MSFT -0.000043  0.954287              0.011117
UAL  -0.000409  1.244163              0.025079

In [125]:
data2 = pd.DataFrame(data1['alpha']/data1['sigma(firm-specific)']**2,columns=['alpha/var'])
data2['weights'] = data2['alpha/var']/np.sum(data2['alpha/var'])
data2.loc['Total'] = data2.sum(numeric_only=True)
data2

       alpha/var   weights
GOOG   -0.784506  0.049268
A       1.643612 -0.103222
RAD    -0.625683  0.039294
SNE     1.911648 -0.120055
LB     -4.757476  0.298777
AAL    -0.991426  0.062263
AAPL   -2.184094  0.137165
JAZZ   -2.068802  0.129924
AMD     2.042885 -0.128297
NVGN    0.242575 -0.015234
UPS    -0.793216  0.049815
MMM    -0.741084  0.046541
GE     -0.935590  0.058757
COST   -6.230173  0.391265
T      -0.845344  0.053089
SCON    1.039766 -0.065299
STZ    -3.556434  0.223350
HPQ     2.710551 -0.170227
MSFT   -0.350615  0.022019
UAL    -0.649739  0.040805
Total -15.923145  1.000000

In [126]:
# Hence the alpha and beta of the active portfolio are 
alpha_p = np.dot(data2['weights'][:-1],data1['alpha'])
beta_p = np.dot(data2['weights'][:-1],data1['beta'])
#Residual variances are
var_residual_p =  np.dot(data2['weights'][:-1]**2,data1['sigma(firm-specific)']**2)
std_residual_p = np.sqrt(var_residual_p)
std_residual_p

0.010336463996380404

In [127]:
#adjusted weight for beta
w0 = (alpha_p/var_residual_p)/((ErM -rf)/(SigmaRM**2))

w_star = w0/(1+(1-beta_p)*w0)
w_star

77.260012596603119

In [128]:
#Position in the index portfolio is 
weight_index = 1- (w_star)
weight_index

-76.260012596603119

In [129]:
# To calculate the Sharpe ratio for the optimal risky portfolio, 
# we compute the information ratio for the active portfolio and Sharpe’s measure for the market portfolio. 
# The information ratio for the active portfolio is computed as follows 

A = alpha_p/std_residual_p
A**2

0.027089543913592067

In [130]:
# Hence, the square of the Sharpe ratio (S) of the optimized risky portfolio is: 
S_sq = ( (ErM-rf)/SigmaRM  )**2 + A**2
S = np.sqrt(S_sq)
S

0.71485767183652393

In [131]:
market_S = (ErM-rf)/SigmaRM  
market_S

0.6956521739130435

In [132]:
# To calculate the makeup of the complete portfolio, first compute the beta, the mean excess return, 
# and the variance of the optimal risky portfolio: 

beta_cp = weight_index + ( w_star*beta_p)
mean_excess_return = w_star*alpha_p+beta_cp*ErM
var_cp = beta_cp**2*SigmaRM**2+w_star**2*var_residual_p
std_cp = np.sqrt(var_cp)
std_cp

3.4685304112619102

In [133]:
# with a coefficient of risk aversion of 2.8?     
# the optimal position in this portfolio is
aversion = 2.8
y = mean_excess_return/(0.01*aversion*var_cp*1000)
y

-0.0073606479142070526

In [134]:
# In contrast, with a passive strategy: 

y1 = (ErM-rf)*100/(0.01*aversion*(SigmaRM*100)**2)
y1

1.0802052389954093